#####################
## eks-spotinstances ##
#####################

.directory_name: &directory-name
  - eu-central-1/eks-spotinstances/*
  - eu-central-1/*.tfvars

.before_script_workernodes: &before-script-workernodes
  - ${GITLAB_CI_SCRIPTS}find_cluster.sh || { echo "Cluster not found, exiting early.." ; exit 0; }

.before_script_global: &before-script-global
  - terraform --version
  - if [ -z ${CI_MERGE_REQUEST_ID} ]; then if [[ ${CI_COMMIT_REF_NAME} == feature* ]]; then export TERRAFORM_ENVIRONMENT=${FEATURE_TERRAFORM_ENVIRONMENT}; else export TERRAFORM_ENVIRONMENT="${CI_COMMIT_REF_NAME}"; fi; else export TERRAFORM_ENVIRONMENT="${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"; fi;
  - cd ${TERRAFORM_DIR}

before_script:
  - *before-script-global

# Target Pipeline
validate:eks-spotinstances:
  extends:
    - .validate
    - .job:eks-spotinstances
  rules:
    - if: "$CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME =~ /^feature/"
      when: never
    - changes: *directory-name
      when: always
    - when: manual

plan:eks-spotinstances:
  extends:
    - .plan
    - .job:eks-spotinstances
  rules:
    - if: "$CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME =~ /^feature/"
      when: never
    - changes: *directory-name
      when: on_success
    - when: manual
  before_script:
    - *before-script-global
    - *before-script-workernodes
  needs:
    - job: validate:eks-spotinstances
      artifacts: true

apply:eks-spotinstances:
  extends:
    - .apply
    - .job:eks-spotinstances
  rules:
    - if: "$CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME =~ /^feature/"
      when: never
    - changes: *directory-name
      when: manual
    - when: manual
  needs:
    - job: plan:eks-spotinstances
      artifacts: true

# MR Pipeline
mr:validate:eks-spotinstances:
  extends:
    - .mr:validate
    - .job:eks-spotinstances

mr:plan:eks-spotinstances:
  extends:
    - .mr:plan
    - .job:eks-spotinstances
  before_script:
    - *before-script-global
    - *before-script-workernodes
  needs:
    - job: mr:validate:eks-spotinstances
      artifacts: true

# Feature Pipeline
feature:validate:eks-spotinstances:
  extends:
    - .feature:validate
    - .job:eks-spotinstances

feature:plan:eks-spotinstances:
  extends:
    - .feature:plan
    - .job:eks-spotinstances
  before_script:
    - *before-script-global
    - *before-script-workernodes
  needs:
    - job: feature:validate:eks-spotinstances
      artifacts: true
